import { type NextPage } from "next";
import Head from "next/head";
import "twin.macro";
import { api } from "~/utils/api";
import { Card, Chips, Layout } from "~/components";
import { useForm, type SubmitHandler } from "react-hook-form";
import { getCsrfToken, signIn } from "next-auth/react";
import type { GetServerSidePropsContext } from "next";
import { type LoginForm } from "types/login-input.types";

const SignIn: NextPage<{ csrfToken: string }> = ({ csrfToken }) => {
  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm<LoginForm>();

  const onSubmit: SubmitHandler<LoginForm> = async (data) => {
    const result = await signIn("credentials", {
      username: data.username,
      password: data.password,
      csrfToken: data.csrfToken,
      redirect: true,
      callbackUrl: "/",
    }).catch((error) => {
      console.log("error", error);
    });
    console.log("login result", result);
  };

  return (
    <>
      <Head>
        <title>登录</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div tw="mt-52">
          <form onSubmit={handleSubmit(onSubmit)}>
            <input
              type="hidden"
              defaultValue={csrfToken}
              {...register("csrfToken")}
            />
            <label>
              Username
              <input type="text" {...register("username")} tw="bg-amber-400" />
            </label>
            <label>
              Password
              <input {...register("password")} tw="bg-amber-400" />
            </label>
            <button type="submit">sign up</button>
          </form>
        </div>
      </Layout>
    </>
  );
};

export default SignIn;

export async function getServerSideProps(context: GetServerSidePropsContext) {
  return {
    props: {
      csrfToken: await getCsrfToken(context),
    },
  };
}
